version: "3"
    
tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o /discordbot main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go -t $BOT_TOKEN

    bot:
        desc: Execute the bot
        cmds:
        - ./discordbot -t $BOT_TOKEN